#!/usr/bin/perl -w
use strict;
use LWP::Simple;
my $url = 'http://www.genenames.org/cgi-bin/download?'.
          'col=gd_hgnc_id&'.
          'col=gd_app_sym&'.
          'col=gd_app_name&'.
          'col=gd_status&'.
          'col=gd_locus_type&'.
          'col=gd_locus_group&'.
          'col=gd_prev_sym&'.
          'col=gd_prev_name&'.
          'col=gd_aliases&'.
          'col=gd_name_aliases&'.
          'col=gd_pub_chrom_map&'.
          'col=gd_date2app_or_res&'.
          'col=gd_date_mod&'.
          'col=gd_date_sym_change&'.
          'col=gd_date_name_change&'.
          'col=gd_pub_acc_ids&'.
          'col=gd_pub_ensembl_id&'.
          'col=gd_other_ids&'.
          'col=gd_other_ids_list&'.
          'col=gd_pubmed_ids&'.
          'col=gd_pub_refseq_ids&'.
          'col=family.id&'.
          'col=family.name&'.
          'col=gd_lsdb_links&'.
          'col=md_mim_id&'.
          'col=md_refseq_id&'.
          'col=md_prot_id&'.
          'col=md_ensembl_id&'.
          'col=md_ucsc_id&'.
          'status=Approved&'.
          'status=Entry%20Withdrawn&'.
          'status_opt=2&'.
          'chr=1&'.
          'chr=2&'.
          'chr=3&'.
          'chr=4&'.
          'chr=5&'.
          'chr=6&'.
          'chr=7&'.
          'chr=8&'.
          'chr=9&'.
          'chr=10&'.
          'chr=11&'.
          'chr=12&'.
          'chr=13&'.
          'chr=14&'.
          'chr=15&'.
          'chr=16&'.
          'chr=17&'.
          'chr=18&'.
          'chr=19&'.
          'chr=20&'.
          'chr=21&'.
          'chr=22&'.
          'chr=X&'.
          'chr=Y&'.
          'where=&'.
          'order_by=gd_app_sym_sort&'.
          'format=text&'.
          'limit=&'.
          'hgnc_dbtag=on&'.
          'submit=submit';
my $page = get($url);
print $page;
