// <auto-generated />
using GeneAnnotationApi.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GeneAnnotationApi.Migrations
{
    [DbContext(typeof(GeneAnnotationDBContext))]
    [Migration("20171213220826_FixedPathogenicSupportCategoryColumnName")]
    partial class FixedPathogenicSupportCategoryColumnName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeneAnnotationApi.Entities.Accession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnName("accession_number")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("GeneId")
                        .HasColumnName("gene_id");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber")
                        .IsUnique()
                        .HasName("UQ__accessio__DD2FB278D74E8212");

                    b.HasIndex("GeneId");

                    b.ToTable("accession");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Annotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("AppUserId")
                        .HasColumnName("app_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("annotation");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AnnotationAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("AnnotationId")
                        .IsRequired()
                        .HasColumnName("annotation_id");

                    b.Property<int?>("AuthorId")
                        .IsRequired()
                        .HasColumnName("author_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("AnnotationId", "AuthorId")
                        .IsUnique()
                        .HasName("unique_annotation_author");

                    b.ToTable("annotation_author");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AnnotationGene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("AnnotationId")
                        .IsRequired()
                        .HasColumnName("annotation_id");

                    b.Property<int?>("GeneId")
                        .IsRequired()
                        .HasColumnName("gene_id");

                    b.HasKey("Id");

                    b.HasIndex("GeneId");

                    b.HasIndex("AnnotationId", "GeneId")
                        .IsUnique()
                        .HasName("unique_annotation_gene");

                    b.ToTable("annotation_gene");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AnnotationGeneVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("AnnotationId")
                        .IsRequired()
                        .HasColumnName("annotation_id");

                    b.Property<int?>("GeneVariantId")
                        .IsRequired()
                        .HasColumnName("gene_variant_id");

                    b.HasKey("Id");

                    b.HasIndex("GeneVariantId");

                    b.HasIndex("AnnotationId", "GeneVariantId")
                        .IsUnique()
                        .HasName("unique_annotation_gene_variant");

                    b.ToTable("annotation_gene_variant");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AnnotationGeneVariantLiterature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("AnnotationId")
                        .IsRequired()
                        .HasColumnName("annotation_id");

                    b.Property<int?>("GeneVariantLiteratureId")
                        .IsRequired()
                        .HasColumnName("gene_variant_literature_id");

                    b.HasKey("Id");

                    b.HasIndex("GeneVariantLiteratureId");

                    b.HasIndex("AnnotationId", "GeneVariantLiteratureId")
                        .IsUnique()
                        .HasName("unique_annotation_gene_variant_literature");

                    b.ToTable("annotation_gene_variant_literature");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AnnotationLiterature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("AnnotationId")
                        .IsRequired()
                        .HasColumnName("annotation_id");

                    b.Property<int?>("LiteratureId")
                        .IsRequired()
                        .HasColumnName("literature_id");

                    b.HasKey("Id");

                    b.HasIndex("LiteratureId");

                    b.HasIndex("AnnotationId", "LiteratureId")
                        .IsUnique()
                        .HasName("unique_annotation_literature");

                    b.ToTable("annotation_literature");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("UQ__app_user__72E12F1BFFA164A6");

                    b.ToTable("app_user");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("UQ__literatu__72E12F1B656D4B26");

                    b.ToTable("author");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AuthorLiterature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("AuthorId")
                        .IsRequired()
                        .HasColumnName("author_id");

                    b.Property<int?>("LiteratureId")
                        .IsRequired()
                        .HasColumnName("literature_id");

                    b.HasKey("Id");

                    b.HasIndex("LiteratureId");

                    b.HasIndex("AuthorId", "LiteratureId")
                        .IsUnique()
                        .HasName("unique_author_literature");

                    b.ToTable("author_literature");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.CallType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("unique_call_type_name")
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("call_type");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.CallTypeGeneVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("ActiveDate")
                        .HasColumnName("active_date")
                        .HasColumnType("datetime");

                    b.Property<int>("CallTypeId")
                        .HasColumnName("call_type_id");

                    b.Property<int>("GeneVariantId")
                        .HasColumnName("gene_variant_id");

                    b.HasKey("Id");

                    b.HasIndex("GeneVariantId");

                    b.HasIndex("CallTypeId", "GeneVariantId")
                        .IsUnique()
                        .HasName("unique_call_type_gene_variant");

                    b.ToTable("call_type_gene_variant");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Chromosome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("UQ__chromoso__72E12F1B32E70F94");

                    b.ToTable("chromosome");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Disorder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("disorder");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.ForeignEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("foreign_entity");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.ForeignIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("ForeignEntityId")
                        .HasColumnName("foreign_entity_id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ForeignEntityId");

                    b.ToTable("foreign_indentity");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.ForeignIdentityGeneCoordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("ForeignIdentityId")
                        .HasColumnName("foreign_identity_id");

                    b.Property<int>("GeneCoordinateId")
                        .HasColumnName("gene_coordinate_id");

                    b.HasKey("Id");

                    b.HasIndex("ForeignIdentityId");

                    b.HasIndex("GeneCoordinateId");

                    b.ToTable("foreign_identity_gene_coordinate");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Gene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("KnownFunction")
                        .HasColumnName("known_function")
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("gene");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneCoordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("End")
                        .HasColumnName("end");

                    b.Property<int>("GeneLocationId")
                        .HasColumnName("gene_location_id");

                    b.Property<int>("Start")
                        .HasColumnName("start");

                    b.HasKey("Id");

                    b.HasIndex("GeneLocationId");

                    b.ToTable("gene_coordinate");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("ChromosomeId")
                        .HasColumnName("chromosome_id");

                    b.Property<int>("GeneId")
                        .HasColumnName("gene_id");

                    b.Property<int>("HgVersion")
                        .HasColumnName("hg_version");

                    b.Property<string>("Locus")
                        .HasColumnName("locus")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChromosomeId");

                    b.HasIndex("GeneId");

                    b.HasIndex("HgVersion", "GeneId")
                        .IsUnique()
                        .HasName("unique_hg_version_gene");

                    b.ToTable("gene_location");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("ActiveDate")
                        .HasColumnName("active_date")
                        .HasColumnType("datetime");

                    b.Property<int?>("GeneId")
                        .HasColumnName("gene_id");

                    b.Property<string>("GeneNameExpansion")
                        .HasColumnName("gene_name_expantion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("GeneId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("UQ__gene_nam__72E12F1BF8484542");

                    b.ToTable("gene_name");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneOriginType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("GeneId")
                        .IsRequired()
                        .HasColumnName("gene_id");

                    b.Property<int?>("OriginTypeId")
                        .IsRequired()
                        .HasColumnName("origin_type_id");

                    b.HasKey("Id");

                    b.HasIndex("OriginTypeId");

                    b.HasIndex("GeneId", "OriginTypeId")
                        .IsUnique()
                        .HasName("unique_gene_origin_type");

                    b.ToTable("gene_origin_type");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("CodingChange")
                        .HasColumnName("coding_change")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("End")
                        .HasColumnName("end");

                    b.Property<int>("Start")
                        .HasColumnName("start");

                    b.Property<int>("VariantTypeId")
                        .HasColumnName("variant_type_id");

                    b.Property<int>("ZygosityTypeId")
                        .HasColumnName("zygosity_type_id");

                    b.HasKey("Id");

                    b.HasIndex("VariantTypeId");

                    b.HasIndex("ZygosityTypeId");

                    b.HasIndex("Start", "End", "CodingChange")
                        .IsUnique()
                        .HasName("uniq_start_end_codingchange")
                        .HasFilter("[coding_change] IS NOT NULL");

                    b.ToTable("gene_variant");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneVariantLiterature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnName("added_at");

                    b.Property<int>("AppUserId")
                        .HasColumnName("app_user_id");

                    b.Property<int>("GeneVariantId")
                        .HasColumnName("gene_variant_id");

                    b.Property<int>("LiteratureId")
                        .HasColumnName("literature_id");

                    b.Property<int>("PathogenicSupportCategoryId")
                        .HasColumnName("pathogenic_support_category_id");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("GeneVariantId");

                    b.HasIndex("LiteratureId");

                    b.HasIndex("PathogenicSupportCategoryId");

                    b.ToTable("gene_variant_literature");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneVarLitDisorder", b =>
                {
                    b.Property<int>("GeneVarLitId")
                        .HasColumnName("gene_var_lit_id");

                    b.Property<int>("DisorderId")
                        .HasColumnName("disorder_id");

                    b.HasKey("GeneVarLitId", "DisorderId")
                        .HasName("PK__gene_var__E586E10FA9F56FED");

                    b.HasIndex("DisorderId");

                    b.ToTable("gene_var_lit_disorder");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.HumanGenomeAssembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("Hg")
                        .IsRequired()
                        .HasColumnName("hg");

                    b.HasKey("Id");

                    b.HasIndex("Hg")
                        .IsUnique()
                        .HasName("human_genome_assembly_hg_uindex");

                    b.ToTable("human_genome_assembly");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Literature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("PubMedId")
                        .HasColumnName("pubMedId")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("url")
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("literature");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.NameSynonym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("ActiveDate")
                        .HasColumnName("active_date");

                    b.Property<int?>("GeneId")
                        .HasColumnName("gene_id");

                    b.Property<string>("Synonum")
                        .IsRequired()
                        .HasColumnName("synonum")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("GeneId");

                    b.HasIndex("Synonum")
                        .IsUnique()
                        .HasName("UQ__name_syn__8E98347ADA10C4C5");

                    b.ToTable("name_synonym");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.OriginType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("unique_origin_type_name")
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("origin_type");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.PathogenicSupportCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("unique_category_name");

                    b.ToTable("pathogenic_support_category");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("ActiveDate")
                        .HasColumnName("active_date")
                        .HasColumnType("datetime");

                    b.Property<int?>("GeneId")
                        .HasColumnName("gene_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GeneId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("UQ__symbol__72E12F1B5A73AE92");

                    b.ToTable("symbol");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Synonym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("ActiveDate")
                        .HasColumnName("active_date")
                        .HasColumnType("datetime");

                    b.Property<int>("GeneId")
                        .HasColumnName("gene_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("GeneId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("UQ__synonym__8E98347A41BDD768");

                    b.ToTable("synonym");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.VariantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ParentId")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("variant_type");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.ZygosityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("uniq_name");

                    b.ToTable("zygosity_type");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Accession", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Gene", "Gene")
                        .WithMany("Accession")
                        .HasForeignKey("GeneId");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Annotation", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.AppUser", "AppUser")
                        .WithMany("Annotation")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AnnotationAuthor", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Annotation", "Annotation")
                        .WithMany("AnnotationAuthor")
                        .HasForeignKey("AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.Author", "Author")
                        .WithMany("AnnotationAuthor")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AnnotationGene", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Annotation", "Annotation")
                        .WithMany("AnnotationGene")
                        .HasForeignKey("AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.Gene", "Gene")
                        .WithMany("AnnotationGene")
                        .HasForeignKey("GeneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AnnotationGeneVariant", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Annotation", "Annotation")
                        .WithMany("AnnotationGeneVariant")
                        .HasForeignKey("AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.GeneVariant", "GeneVariant")
                        .WithMany("AnnotationGeneVariant")
                        .HasForeignKey("GeneVariantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AnnotationGeneVariantLiterature", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Annotation", "Annotation")
                        .WithMany("AnnotationGeneVariantLiterature")
                        .HasForeignKey("AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.GeneVariantLiterature", "GeneVariantLiterature")
                        .WithMany("AnnotationGeneVariantLiterature")
                        .HasForeignKey("GeneVariantLiteratureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AnnotationLiterature", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Annotation", "Annotation")
                        .WithMany("AnnotationLiterature")
                        .HasForeignKey("AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.Literature", "Literature")
                        .WithMany("AnnotationLiterature")
                        .HasForeignKey("LiteratureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.AuthorLiterature", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Author", "Author")
                        .WithMany("AuthorLiterature")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.Literature", "Literature")
                        .WithMany("AuthorLiterature")
                        .HasForeignKey("LiteratureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.CallTypeGeneVariant", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.CallType", "CallType")
                        .WithMany("CallTypeGeneVariants")
                        .HasForeignKey("CallTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.GeneVariant", "GeneVariant")
                        .WithMany("CallTypeGeneVariants")
                        .HasForeignKey("GeneVariantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.ForeignIdentity", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.ForeignEntity", "ForeignEntity")
                        .WithMany("ForeignIdentities")
                        .HasForeignKey("ForeignEntityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.ForeignIdentityGeneCoordinate", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.ForeignIdentity", "ForeignIdentity")
                        .WithMany("ForeignIdentityGeneCoordinates")
                        .HasForeignKey("ForeignIdentityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.GeneCoordinate", "GeneCoordinate")
                        .WithMany("ForeignIdentityGeneCoordinates")
                        .HasForeignKey("GeneCoordinateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneCoordinate", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.GeneLocation", "GeneLocation")
                        .WithMany("GeneCoordinates")
                        .HasForeignKey("GeneLocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneLocation", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Chromosome", "Chromosome")
                        .WithMany("GeneLocations")
                        .HasForeignKey("ChromosomeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.Gene", "Gene")
                        .WithMany("GeneLocations")
                        .HasForeignKey("GeneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneName", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Gene", "Gene")
                        .WithMany("GeneName")
                        .HasForeignKey("GeneId");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneOriginType", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Gene", "Gene")
                        .WithMany("GeneOriginType")
                        .HasForeignKey("GeneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.OriginType", "OriginType")
                        .WithMany("GeneOriginType")
                        .HasForeignKey("OriginTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneVariant", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.VariantType", "VariantType")
                        .WithMany("GeneVariant")
                        .HasForeignKey("VariantTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.ZygosityType", "ZygosityType")
                        .WithMany("GeneVariant")
                        .HasForeignKey("ZygosityTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneVariantLiterature", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.AppUser", "AppUser")
                        .WithMany("GeneVariantLiteratures")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.GeneVariant", "GeneVariant")
                        .WithMany("GeneVariantLiterature")
                        .HasForeignKey("GeneVariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.Literature", "Literature")
                        .WithMany("GeneVariantLiteratures")
                        .HasForeignKey("LiteratureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.PathogenicSupportCategory", "PathogenicSupportCategory")
                        .WithMany("GeneVariantLiteratures")
                        .HasForeignKey("PathogenicSupportCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.GeneVarLitDisorder", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Disorder", "Disorder")
                        .WithMany("GeneVarLitDisorder")
                        .HasForeignKey("DisorderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeneAnnotationApi.Entities.GeneVariantLiterature", "GeneVarLit")
                        .WithMany("GeneVarLitDisorder")
                        .HasForeignKey("GeneVarLitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.NameSynonym", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Gene", "Gene")
                        .WithMany("NameSynonym")
                        .HasForeignKey("GeneId");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Symbol", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Gene", "Gene")
                        .WithMany("Symbol")
                        .HasForeignKey("GeneId");
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.Synonym", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.Gene", "Gene")
                        .WithMany("Synonym")
                        .HasForeignKey("GeneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeneAnnotationApi.Entities.VariantType", b =>
                {
                    b.HasOne("GeneAnnotationApi.Entities.VariantType", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
